### ISSUE TITLE
yarn dev 报错

### ISSUE THREAD

**Issue by xyj2156** [920200256/bianquan-blog#1]
https://github.com/920200256/bianquan-blog/blob/45e3f76705b30d8c8d87f7c07e4505e57b8705c1/src/components/write.vue#L62

我不知道这儿为什么这样写，我修改成这样就ok 了。
`import index from 'vue';`

**Comment by 920200256** [comment]
额， 这句 import index from '../../node_modules/_vue@2.5.16@vue'; 并不是我写进去的，我也没发觉到有这句，搞不懂怎么就加进去了，我本地直接运行没问题，删掉这句也不影响。
