### ISSUE TITLE
首次打开首页，标签不显示问题。

### ISSUE THREAD

**Issue by xyj2156** [920200256/bianquan-blog#2]
> 这儿的判断有问题导致 标签不能正常 渲染
https://github.com/920200256/bianquan-blog/blob/45e3f76705b30d8c8d87f7c07e4505e57b8705c1/src/components/aside.vue#L163

原因：初始化的时候 赋值的是一个数组，js 中 空数组也是 `true`
https://github.com/920200256/bianquan-blog/blob/45e3f76705b30d8c8d87f7c07e4505e57b8705c1/src/vuex/state.js#L29

**Comment by 920200256** [comment]
多谢提醒，我这边一直能渲染出来，没想到犯了这个错误。

**Comment by xyj2156** [comment]
> 我这几天打算 `phalcon` 写个后台，请求方法和您的有出入。我的方式 从一个URL 请求所有用到的URL，然后做了一个中间层兼容您的方法。

**Comment by 920200256** [comment]
博客站用这个前台对于SEO来说非常不友好，这个是我的第一个项目，实在简陋，现在看来写博客还是用传统的MVC来写会方便些。
