### ISSUE TITLE
请教部署问题

### ISSUE THREAD

**Issue by wqcai** [920200256/bianquan-blog#4]
请教下，怎么部署的呢？build之后没有html文件？然后又是怎么跟php结合的呢？两个服务器？

**Comment by 920200256** [comment]
vue部署生产环境可以参考官方文档，这个项目初始化使用webpack-sipmail模板，build后要将dis文件夹和原来的index.html拷贝到服务器网页根目录即可，线上只要支持php服务器即可，网站根目录文件为dist、servers、static三个文件夹和index.html文件，还有就是别忘了更改axios请求路劲地址。
